### ISSUE TITLE
Metromover data

### ISSUE THREAD

**Issue by bruncun** [Code-for-Miami/LeafletTransit#48]
Is this easily doable? As a rider myself would love to switch from using the transit app to the leaflet app.

**Comment by qtrandev** [comment]
Try this link: http://www.miamidade.gov/transit/WebServices/MoverTracker/?StationID=

The rest of the links are in this doc: http://www.miamidade.gov/transit/WebServices/Transit_XML_Data_Feeds.pdf

**Comment by qtrandev** [comment]
Our miami transit api may already turn this data to JSON.
